# Generated by Django 5.2.3 on 2025-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
